name: ${project.parent.artifactId}
author: Arhke
version: ${project.version}
api-version: 1.16
main: com.Arhke.ArhkeLib.ArhkeLib
softdepend: [PlaceholderAPI, NBTAPI, Vault, Essentials, WorldEdit, WorldGuard, Cannons]